### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by TomSpencerLondon** [mhlabs/sam-patterns-cli#1]
I get this error after npm install sam-patterns-cli -g:
```code
sam-patterns import                                 main s3-terraform-practice
(node:51879) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /usr/local/lib/node_modules/sam-patterns-cli/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (/usr/local/lib/node_modules/sam-patterns-cli/src/commands/import/import.js:22:20)
    at async Command.<anonymous> (/usr/local/lib/node_modules/sam-patterns-cli/src/commands/import/index.js:9:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ljacobsson** [comment]
Thanks for reporting!

Try setting environment variable `GITHUB_TOKEN` to your [Github token](https://github.com/settings/tokens).

The [Github API](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) only allows for 60 requests per hour if unauthenticated. 

However, this tool should still allow for unauthenticated access and not throw an error

**Comment by ljacobsson** [comment]
Version 0.0.3 fixes this.

Please reopen if you're still facing issues
